name: Sync flutter docker

on:
  push:
    branches: [ "*" ]
  # schedule:
  #   - cron: 0 */6 * * *

env:
  DOCKER_COM_VERSION: 0

jobs:
  get_docker_version:
    runs-on: cirrusci/flutter
    steps:
      - name: Check Docker's version
        run: echo $(docker --version)